### ISSUE TITLE
Include Æ, Ø, Å in internal website

### ISSUE THREAD

**Issue by GryMGr** [folkehelseinstituttet/dashboards_sykdomspuls#75] opened 2019-04-02 09:31 UTC
Æ, Ø and Å does not show on the internal website.

**Comment by raubreywhite** [comment] 2019-04-23 15:43
@Gulfa Please take a look at this:

https://github.com/folkehelseinstituttet/dashboards_sykdomspuls/commit/dd5306d04fd61fe1f607e761cc15778951b3655d

I just went through and deleted all åøæ from the dashboard. This is because the moment we type åæø into the dashboard, the rest of the website is ignored.

So if you look at https://github.com/folkehelseinstituttet/dashboards_sykdomspuls/blob/961ac7868141ce727f1c16af92e23e6cd721dc1d/inst/shiny/sykdomspuls/flexdashboard.Rmd#L274

The website literally stops after: "Valg av tidsrom gj"

I have tried putting in the unicode versions (e.g. \u00F8) and the normal "å", but they both result in the website just not being read into shiny. I've also made sure that the file is saved in UTF-8.

To run this yourself, just go to:

https://github.com/folkehelseinstituttet/dashboards_sykdomspuls/blob/master/inst/src/RunInternalDashboard.R

And then run the entire script. You can then access this at: localhost:4989

PS. Make sure that you've run the entire "RunProcess.R" first, because this will generate the results and saves them into the SQL database, which is the source of all the results.

I'm really confused as to what the problem is, because this all used to work perfectly. I'm fairly sure that it has something to do with us upgrading a version of something...???

**Comment by Gulfa** [comment] 2019-05-03 13:19
It looks to me like it works when I use the HTML encoding instead of the unicode encoding. I.e 
ø = &#248;
æ = &#230;
å = &#229;

Maybe you can verify that this works for you too before I replace all the old text with this. 

That said, I think there still is something strange happening with the character encoding somewhere. When I just created a simple flexdashboard i could use æøå without any extra encoding. This would make writing the text easier so will try to continue to understand why this encoding issue happens.

**Comment by raubreywhite** [comment] 2019-05-03 16:31
Maybe you can try just copy/pasting some of our code into a new
flexdashboard .Rmd file that has the proper UTF-8 encoding? It's a really
weird problem.

Oh! This is also important, you need to check that the åøæ display properly
on a windows computer. At one point it worked properly on a mac and linux,
but didn't display on windows computers. And then it stopped working all
together....

You'll get a windows laptop once you get to Oslo, so please see if you can
get the website to load on that laptop :-)

**Comment by Gulfa** [comment] 2019-05-07 13:22
I did try to copy some of the code into a new flexdashboard and then it worked fine. So most be something about the encoding at some point in the process. Will investigate the issue more carefully this week and check if my fix above works on a windows laptop. Realised that my post above looks a bit stupid since the html encoding I included in it get's rendered by the browser.

**Comment by Gulfa** [comment] 2019-05-15 12:16
I think we have found a fix for this issue now. It requires changes to the docker infrastructure that richard will review when he is back.

**Closed** 2019-06-06 08:25 UTC
